package interpreter.ast;

public enum NodeType {
    INTEGER,
    PROGRAM,
    EXPRESSION_STATEMENT,
    BOOLEAN,
    NULL,
    INFIX_EXPRESSION,
    BLOCK_STATEMENT,
    IF_EXPRESSION,
    RETURN_STATEMENT,
    LET_STATEMENT,
    PREFIX_EXPRESSION,
    IDENTIFIER,
    FUNCTION_LITERAL,
    CALL_EXPRESSION,
    STRING,
    ARRAY_LIST,
    INDEX_EXPRESSION,
    HASH;
}
