/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interpreter;

import interpreter.repl.Repl;

public class App {

    public static void main(String[] args) {
        new Repl().start(System.in, System.out);
    }
}
